sowafinance/expenses/urls.py
from django.urls import path
from . import views
app_name='expenses'
# my urls
urlpatterns = [  
# expenses urls
    path('expenses/', views.expenses, name='expenses'),
    path('expenses/add/time-activity', views.add_time_activity, name='time-activity'),
    path('expenses/add/bill', views.add_bill, name='add-bill'),
    path('expenses/supplier-credit', views.supplier_credit, name='supplier-credit'),
    path('expenses/add/purchase_order', views.purchase_order, name='purchase_order'),
    path('expenses/pay_down_credit', views.pay_down_credit, name='pay-down-credit'),
    path('expenses/import_bills', views.import_bills, name='import-bills'),
    path('expenses/credit_card', views.credit_card, name='credit-card'),
    path('expenses/add/cheque', views.add_cheque, name='add-cheque'),
    path('expenses/add/expenses', views.add_expenses, name='add-expenses'),
]

sowafinance/sales/urls.py
from django.urls import path
from . import views


app_name='sales'
# my urls
urlpatterns = [  
# sales urls
    path('sales/', views.sales, name='sales'),
    path('sales/add/invoice', views.add_invoice, name='add-invoice'),
    path('sales/add/receipts', views.add_receipt, name='add-receipt'),
    path('sales/add/payments', views.add_payment, name='add-payments'),
    path('sales/add/invoice', views.add_invoice, name='add-invoice'),
    path('sales/invoices/', views.invoice_list, name='invoices'),
    path('sales/full-invoice-details/', views.full_invoice_details, name='full-invoice-details'),
    path('sales/individual-invoice/', views.individual_invoice, name='individual-invoice'),
    # path('receipts/', views.receipt, name='receipts'),
    path('receipts/add/receipt', views.add_receipt, name='add-receipt'),
    # path('payments/', views.payment, name='payments'),
    path('payments/add/payment', views.add_payment, name='add-payment'),
]

sowafinance/sowaf/urls.py
from django.urls import path
from . import views


app_name='sowaf'
# my urls
urlpatterns = [
    path('home/', views.home, name='home'),
    
    # asset urls
    path('assets/', views.assets, name='assets'),
    path('assets/add/asset', views.add_assests, name='add-asset'),
    path('assets/edit/<str:pk>/', views.edit_asset, name='edit-asset'),
    path('assets/delete/<str:pk>/', views.delete_asset, name='delete-asset'),
    path('assets/import/import-assets', views.import_assets, name='import-assets'),
    path('templates/assets/', views.download_assets_template, name='import_assets_template'),
    
    # customer urls
    path('customers/', views.customers, name='customers'),
    path('customers/add/', views.add_customer, name='add-customer'),
    path('customers/edit/<str:pk>/', views.edit_customer, name='edit-customer'),
    path('customers/delete/<str:pk>/', views.delete_customer, name='delete-customer'),
    path('customers/import/import-customers', views.import_customers, name='import-customers'),
    path('templates/customers/', views.download_customers_template, name='import_customers_template'),
    
    # clents urls
    path('clients/', views.clients, name='clients'),
    path('clients/add/', views.add_client, name='add-client'),
    path('clients/edit/<str:pk>/', views.edit_client, name='edit-client'),
    path('clients/delete/<str:pk>/', views.delete_client, name='delete-client'),
    path('clients/import/import-clients', views.import_clients, name='import-clients'), 
    path('templates/clients/', views.download_clients_template, name='import_clients_template'),
    
    # employee urls
    path('employees/', views.employee, name='employees'),
    path('employees/add/employee', views.add_employees, name='add-employee'),
    path('employees/edit/<str:pk>/', views.edit_employee, name='edit-employee'),
    path('employees/delete/<str:pk>/', views.delete_employee, name='delete-employee'),
    path('employees/import/import-employees', views.import_employees, name='import-employees'),
    path('templates/employees/', views.download_employees_template, name='import_employees_template'),
  
    # supplier urls
    path('suppliers/', views.supplier, name='suppliers'),
    path('suppliers/add/supplier', views.add_supplier, name='add-supplier'),
    path('suppliers/edit/<str:pk>', views.edit_supplier, name='edit-supplier'),
    path('suppliers/delete/<str:pk>', views.delete_supplier, name='delete-supplier'),
    path('suppliers/import/import-suppliers', views.import_suppliers, name='import-suppliers'),
    path('templates/suppliers/', views.download_suppliers_template, name='import_suppliers_template'),
    
 
        # expenses url
    path('expenses/', views.expenses, name='expenses'),
    # tasks url
    path('tasks/', views.tasks, name='tasks'),
    # taxes url
    path('taxes/', views.taxes, name='taxes'),

    # -------------------
    path('miscellaneous/', views.miscellaneous, name='miscellaneous'),
    # -------------
    path('reports/', views.reports, name='reports'),
    # -----------------
    
]

sowafinance/sowafinance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('sowaAuth.urls')),  # login, register, otp, etc.
    path('sowaAuth/', include('django.contrib.auth.urls')),
    # Nest all app URLs under 'sowaf/'
    path('sowaf/', include([
        path('', include('sowaf.urls')),         # dashboard and home
        path('sales/', include('sales.urls')),   # sales module
        path('expenses/', include('expenses.urls')),  # expenses
        path('inventory/', include('inventory.urls')),  # inventory
    ])),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sowafinance/accounts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

class Account(models.Model):
    ACCOUNT_TYPES = [
        ("ASSET", "Asset"),
        ("LIABILITY", "Liability"),
        ("EQUITY", "Equity"),
        ("INCOME", "Income"),
        ("EXPENSE", "Expense"),
    ]
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=20, unique=True)  # e.g. 1000 for Cash
    type = models.CharField(max_length=20, choices=ACCOUNT_TYPES)

    def __str__(self):
        return f"{self.code} - {self.name}"


class Transaction(models.Model):
    date = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=255,null=True)

    def __str__(self):
        return f"{self.date} - {self.description}"

    @property
    def total_debits(self):
        return sum(entry.debit for entry in self.entries.all())

    @property
    def total_credits(self):
        return sum(entry.credit for entry in self.entries.all())


class Entry(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, related_name="entries")
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    debit = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    credit = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.account} | Dr {self.debit} Cr {self.credit}"

# accounts/models.py

class BankTransaction(models.Model):
    TYPE_CHOICES = [('deposit','Deposit'),('withdrawal','Withdrawal')]
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    date = models.DateField(auto_now_add=True)
    
class SupplierPayment(models.Model):
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    from_bank = models.ForeignKey('BankTransaction', on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(auto_now_add=True)
    
class Loan(models.Model):
    TYPE_CHOICES = [('disbursement','Disbursement'),('repayment','Repayment')]
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    date = models.DateField(auto_now_add=True)

sowafinance/accounts/views.py
from django.shortcuts import render

# Create your views here.

sowafinance/accounts/templates/Clients.html
{% load static %}

{% include 'includes/navbar.html' %}
<style>
    h1{
    color: rgb(7, 142, 36);
  }
    @media only screen and (max-width: 600px) {
  #action{
    background-color: #fff;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    padding:10%;
    justify-content: center;
  }
  #action button{
    display: flex;
  }
     #search{
    display: flex;
    width: 50%;
    margin-top: 0px;
  }
  h1{
    color: rgb(7, 142, 36);
    font-size: 20px;
  }
  .button{
    width: 100px;
  }
  #main{
    padding: 15%;
    margin-left: -20%;
    margin-top: 65%;
  }
  #template{
    position: fixed;
    margin-top:-3%;
    margin-left:70%;
  }
}
</style>
{% include 'includes/sidebar.html' %}
    <div class="action" id="action">
      <h1>CLIENTS</h1>
      <div class="search_bar" id="search">
        <input type="text" placeholder="Search Clients" />
      </div>

      <a href="{% url 'sowaf:add-client' %}" style="text-decoration: none;">
         <button class="button">
          <span class="button_text">ADD NEW</span>
          <span class="button_icon">
            <i class='bx bx-folder-plus'></i>
          </span>
        </button>
        </a>
        <div>
       <form action="{% url 'sowaf:import-clients' %}" method="POST" enctype="multipart/form-data" style="display: flex;">
         {% csrf_token %}
    
        <input type="file" name="excel_file" accept=".xlsx, .xls, .csv" required style="display: none;" id="excelInput" onchange="this.form.submit()" />
        <label for="excelInput" class="button" style="cursor: pointer;">
         <span class="button_text">IMPORT</span>
        <span class="button_icon">
        <i class='bx bx-import'></i>
        </span>
       </label>
         </form>
       </div>
      <a href="{% url 'sowaf:add-customer' %}" style="text-decoration: none;">
         <button class="button">
          <span class="button_text">EXPORT</span>
          <span class="button_icon">
            <i class='bx bx-folder-plus'></i>
          </span>
        </button>
      </a>
        <button class="button" onclick="openColumnCustomizer()">
         <span class="button_text">CUSTOMIZE</span>
         <span class="button_icon">
         <i class='bx bxs-customize'></i>
          </span>
        </button>
    </div>
    <div class="main_body" id="main">
      <table class="content-table">
        <thead>
          <tr>
            <th>LOGO</th>
            <th>ID</th>
            <th>COMPANY NAME</th>
            <th>PHONE</th>
            <th>EMAIL</th>
            <th>CREDIT LIMIT</th>
            <th>STATUS</th>
            <th>OPERATIONS</th>
          </tr>
        </thead>
        <tbody>
          {% for client in clients %}
          <tr>
            <td>
                  {%if client.logo %}
              <img src=" {{ client.logo.url }}" alt="picture" style="width: 40px; height: 40px; border-radius: 50%;">
              {% else %}
              <i class='bx bx-user-circle'></i>
              {% endif %}
              </td>
            </i>
          </td>
            <td>{{client.id|stringformat:"03d"}}</td>
            <td>{{client.company}}</td>
            <td>{{client.phone}}</td>
            <td>{{client.company_email}}</td>
            <td>{{client.credit_limit}}</td>
            <td>{{client.status}}</td>
            <td>
            <a href="{% url 'sowaf:edit-client' client.id %}" title="Edit" style="color:green;">
              <i class='bx bxs-edit'></i> 
              </a>
                <a href="{% url 'sowaf:delete-client' client.id %}" title="Delete" onclick="return confirm('Are you sure you want to delete this customer?');">
               <i class='bx bxs-trash' style="color:green; margin-left: 10px;"></i>
               </a>

            </td>
          </tr>
        {% empty %}    
        <tr>
      <td colspan="6">No customers available.</td>
    </tr>
     <tr>
      <td colspan="6">
      {% if messages %}
      {% for message in messages %}
        {% if messages.tags == 'error' %}
        <p style="color:green; text-align:center;">{{message}}</p>
        {% else %}
        <p style="color:green; text-align:center;">{{message}}</p>
        {% endif %}
      {% endfor %}
    {% endif %}
      </td>
    </tr>
         {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'sowaf:import_clients_template' %}" style="text-decoration: none; float:right;" id="template">
        <button class="button">
          <span class="button_text">Template</span>
        </button>
      </a>
    </div>

<script>
  function openColumnCustomizer() {
    document.getElementById('columnCustomizerModal').style.display = 'block';
  }

  function closeColumnCustomizer() {
    document.getElementById('columnCustomizerModal').style.display = 'none';
  }

  // Optional: close modal when clicking outside
  window.onclick = function(event) {
    const modal = document.getElementById('columnCustomizerModal');
    if (event.target == modal) {
      closeColumnCustomizer();
    }
  }
</script>
 {% include 'includes/footer.html' %}

sowafinance/accounts/templates/Customers.html
{% load static %}
{% include 'includes/navbar.html' %}
<style>
      h1{
    color: rgb(7, 142, 36);
  }
    @media only screen and (max-width: 600px) {
  #action{

    background-color: #fff;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    padding:10%;
  }
  #action button{
    display: flex;
  }
     #search{
    display: flex;
    width: 50%;
    margin-top: 0px;
  }
  h1{
    color: rgb(7, 142, 36);
    font-size: 20px;
  }
  .button{
    width: 100px;
  }
  #main{
    padding: 15%;
    margin-left: -20%;
    margin-top: 70%;
    margin-right: 1%;
  }
  #template{
    position: fixed;
    margin-left:70%;
  }
}
</style>
{% include 'includes/sidebar.html' %}
    <div class="action" id="action">
      <h1>CUSTOMER</h1>
      <div class="search_bar" id="search">
        <input type="text" placeholder="Search customers" />
      </div>

      <a href="{% url 'sowaf:add-customer' %}" style="text-decoration: none;">
         <button class="button">
          <span class="button_text">ADD NEW</span>
          <span class="button_icon">
            <i class='bx bx-folder-plus'></i>
          </span>
        </button>
        </a>
        <div>
       <form action="{% url 'sowaf:import-customers' %}" method="POST" enctype="multipart/form-data" style="display: flex;">
         {% csrf_token %}
        <input type="file" name="excel_file" accept=".xlsx, .xls, .csv" required style="display: none;" id="excelInput" onchange="this.form.submit()" />
        <label for="excelInput" class="button" style="cursor: pointer;">
         <span class="button_text">IMPORT</span>
        <span class="button_icon">
        <i class='bx bx-import'></i>
        </span>
       </label>
         </form>
       </div>
      <a href="{% url 'sowaf:add-customer' %}" style="text-decoration: none;">
         <button class="button">
          <span class="button_text">EXPORT</span>
          <span class="button_icon">
            <i class='bx bx-folder-plus'></i>
          </span>
        </button>
      </a>
      <button class="button">
          <span id="customize" class="button_text">CUSTOMIZE</span>
          <span id="customize" class="button_icon">
            <i class='bx bxs-customize' ></i>
          </span>
        </button>
          <span>
            <i class='bx bx-printer'></i>
            <i class='bx bx-customize'></i>
            <i class='bx bx-cog' ></i>
          </span>
    </div>
    <div class="main_body" id="main">
      <table class="content-table">
        <thead>
          <tr>
            <th>PROFILE ICON</th>
            <th>NAME</th>
            <th>COMPANY NAME</th>
            <th>OPEN BALANCE</th>
            <th>OPERATIONS</th>
            <th>ACTIONS <i class='bx bxs-down-arrow' ></i></th>
          </tr>
        </thead>
        <tbody>
        {% for customer in customers %}
          <tr>
            
            <td>
              {%if customer.logo %}
              <img src=" {{ customer.logo.url }}" alt="picture" style="width: 40px; height: 40px; border-radius: 50%;">
              {% else %}
              <i class='bx bx-user-circle'></i>
              {% endif %}
              </td>
            <td>{{customer.customer_name}}</td>
            <td>{{customer.company_name}}</td>
            <td>{{customer.opening_balance}}</td>
            <td>
              <a href="{% url 'sowaf:edit-customer' customer.id %}" title="Edit" style="color:green;">
              <i class='bx bxs-edit'></i> 
                </a>
                <a href="{% url 'sowaf:delete-customer' customer.id %}" title="Delete" onclick="return confirm('Are you sure you want to delete this customer?');">
               <i class='bx bxs-trash' style="color:green; margin-left: 10px;">

    </i>
  </a>
            </td>
            <td><a>{{customer.actions}}</a></td>
          </tr>   
          {% empty %}    
                <tr>
      <td colspan="6">No customers available.</td>
    </tr>
         {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'sowaf:import_customers_template' %}" style="text-decoration: none; float:right;" id="template">
        <button class="button">
          <span class="button_text">Template</span>
        </button>
      </a>
    </div>
{% include 'includes/footer.html' %}

sowafinance/accounts/templates/Employees.html
{% load static %}
{% include 'includes/navbar.html' %}
<style>
      h1{
    color: rgb(7, 142, 36);
  }
    @media only screen and (max-width: 600px) {
  #action{
    background-color: #fff;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    padding:10%;
    justify-content: center;
  }
  #action button{
    display: flex;
  }
     #search{
    display: flex;
    width: 50%;
    margin-top: 0px;
  }
  h1{
    color: rgb(7, 142, 36);
    font-size: 20px;
  }
  .button{
    width: 100px;
  }
  #main{
    padding: 15%;
    margin-left: -20%;
    margin-top: 65%;
  }
  #template{
    position: fixed;
    margin-top:-3%;
    margin-left:70%;
  }
}
</style>
{% include 'includes/sidebar.html' %}
    <div class="action" id="action">
      <h1>EMPLOYEES</h1>
      <div class="search_bar" id="search">
        <input type="text" placeholder="Search Employees" />
      </div>
      <a href="{% url 'sowaf:add-employee' %}" style="text-decoration: none;">
        <button class="button">
          <span class="button_text">ADD NEW</span>
          <span class="button_icon">
            <i class='bx bx-folder-plus'></i>
          </span>
        </button>
      </a>
      <div>
       <form action="{% url 'sowaf:import-employees' %}" method="POST" enctype="multipart/form-data" style="display: flex;">
         {% csrf_token %}
        <input type="file" name="excel_file" accept=".xlsx, .xls, .csv" required style="display: none;" id="excelInput" onchange="this.form.submit()" />
        <label for="excelInput" class="button" style="cursor: pointer;">
         <span class="button_text">IMPORT</span>
        <span class="button_icon">
        <i class='bx bx-import'></i>
        </span>
       </label>
         </form>
       </div>
      </a>
            <a href="{% url 'sowaf:add-employee' %}" style="text-decoration: none;">
        <button class="button">
          <span class="button_text">EXPORT</span>
          <span class="button_icon">
            <i class='bx bx-folder-plus'></i>
          </span>
        </button>
      </a>
        <button class="button">
          <span class="button_text">CUSTOMIZE</span>
          <span class="button_icon">
            <i class='bx bx-cog' ></i>
          </span>
        </button>
    </div>
    <div class="main_body" id="main">
      <table class="content-table">
        <thead>
          <tr>
            <th>PROFILE PICTURE</th>
            <th>ID</th>
            <th>DISPLAY NAME</th>
            <th>PHONE</th>
            <th>EMAIL</th>
            <th>STATUS</th>
            <th>OPERATIONS</th>
            <th>ACTIONS</th>
          </tr>
        </thead>
        <tbody>
          {% for employee in employees %}
          <tr>
            <td>
            {%if employee.profile_picture %}
              <img src=" {{ employee.profile_picture.url }}" alt="picture" style="width: 40px; height: 40px; border-radius: 50%;">
              {% else %}
              <i class='bx bx-user-circle'></i>
              {% endif %}
            </td>
            <td>{{employee.id|stringformat:'03d'}}</td>
            <td>{{employee.first_name}} {{employee.last_name}} </td>
            <td>{{employee.phone_number}}</td>
            <td>{{employee.email_address}}</td>
            <td>{{employee.status}}</td>
            <td>
              <a href="{% url 'sowaf:edit-employee' employee.id %}" title="Edit" style="color:green;">
              <i class='bx bxs-edit'></i> 
              </a>
                <a href="{% url 'sowaf:delete-employee' employee.id %}" title="Delete" onclick="return confirm('Are you sure you want to delete this customer?');">
               <i class='bx bxs-trash' style="color:green; margin-left: 10px;"></i>
               </a>
            </i></td>
            <td>Retire/inactive</td>
          </tr>
          
           {% empty %}    
        <tr>
      <td colspan="6">No customers available.</td>
    </tr>
    <tr>
      <td colspan="6">
      {% if messages %}
      {% for message in messages %}
        {% if messages.tags == 'error' %}
        <p style="color:green; text-align:center;">{{message}}</p>
        {% else %}
        <p style="color:green; text-align:center;">{{message}}</p>
        {% endif %}
      {% endfor %}
    {% endif %}
      </td>
      
         {% endfor %}
        </tbody>
      </table>
    <a href="{% url 'sowaf:import_employees_template' %}" style="text-decoration: none; float-right" id="template" >
        <button class="button">
          <span class="button_text">Template</span>
        </button>
      </a>
    </div>
{% include 'includes/footer.html' %}

sowafinance/accounts/templates/Home.html
{% load static %}
{% include 'includes/navbar.html' %}
  <style>
    @media only screen and (max-width: 600px) {
  #action{
    height: 50px;
    width: 20px;
    background-color: green;
    margin-left: 10%;
    display: flex;
    flex-wrap: 1px;
    justify-content: space-between;
    margin-top: 5%;
  }
   #search{
    display: flex;
    width: 40%;
    margin-top: 0px;
  }
  h1{
    color: white;
  }
  .tabs{
    margin-top: 10%;
  }
  .button{
    width: 30%;
    height: 5vh;
  }

  #main_body {
width: 100%;
margin: 0;
padding-top: 35%;
height: 100vh;

}
  #items{
display: block;
margin: -3%;
padding: 3%;
}
#things{
   margin: 3%;
   width: 100%;
   
}
#Overview{
display: block;
margin-right: 5%;
padding: 3%;
}
.overviews{
   margin: 3%;
   width: 100%;
}
}
</style>
{% include 'includes/sidebar.html' %}
    <div class="action" id="action">
      <h1>HOME</h1>
      <div class="search_bar" id="search">
        <input type="text" placeholder="Search Home" />
      </div>
        <button class="button">
          <span id="customize" class="button_text">CUSTOMIZE</span>
          <span id="customize" class="button_icon">
            <i class='bx bxs-customize' ></i>
          </span>
        </button>
    </div>
    <div class="main_body" id="main_body">


      <div class="tabs">
        <input type="radio" class="tabs_radio" name="tabs-example" id="tab1" checked>
        <label for="tab1" class="tabs_label">Get things done</label>
            <div class="tab-content">
              <div id="Overview">
                <a href="{% url 'sales:add-receipt' %}" style="text-decoration:none"><div class="overviews" id=""><i class='bx bx-receipt'></i>Add receipt</div></a>
                <a href="{% url 'sowaf:add-supplier' %}" style="text-decoration:none"><div class="overviews" id=""><i class='bx bxs-truck' ></i>Add supplier</div></a>
                <a href="{% url 'expenses:add-expenses' %}" style="text-decoration:none"><div class="overviews" id=""><i class='bx bx-money-withdraw' ></i>Add expense</div></a>
                <a href="{% url 'expenses:add-bill' %}" style="text-decoration:none"><div class="overviews" id=""><i class='bx bx-credit-card'></i>Add bill</div></a>
                <a href="" style="text-decoration:none"><div class="overviews" id=""><i class='bx bx-credit-card'></i>Pay bill</div></a>
                <a href="{% url 'expenses:add-expenses' %}" style="text-decoration:none"><div class="overviews" id=""><i class='bx bx-user-voice'></i>Add customer</div></a>
                <a href="{% url 'sales:add-invoice' %}" style="text-decoration:none"><div class="overviews" id=""><i class='bx bx-file'></i>Add invoice</div></a>
                <a href="" style="text-decoration:none"><div class="overviews" id=""><i class='bx bx-timer' ></i>Track time</div></a>
              </div>
            </div>
          <input type="radio" class="tabs_radio" name="tabs-example" id="tab2">
          <label for="tab2" class="tabs_label">Business Overview</label>
            <div class="tab-content">
              <div id="Overview">
                <div class="overviews" id="Account-balance">Bank Account Balance</div>
                <div class="overviews" id="Sales-overview">Sales</div>
                <div class="overviews" id="Expenses-overview">Expenses</div>
                <div class="overviews" id="Invoices">Invoices</div>
                <div class="overviews" id="Outstanding-bills">Outstanding Bills</div>
                <div class="overviews" id="Profit-loss">Profit and Loss</div>
              </div>
            </div>
      </div>
    </div>
 {% include 'includes/footer.html' %}

sowafinance/accounts/templates/Reports.html
{% load static %}
{% include 'includes/navbar.html' %}
{% include 'includes/sidebar.html' %}
    <div class="action">
      <H1>REPORTS</H1>
      <div class="search_bar">
        <input type="text" placeholder="Search Reports" />
      </div>
        <button class="button">
          <span class="button_text">CUSTOMIZE</span>
          <span class="button_icon">
            <i class='bx bxs-customize' ></i>
          </span>
        </button>
    </div>
    <div class="main_body">

      <div class="tabs">
        <input type="radio" class="tabs_radio" name="tabs-example" id="tab1" checked>
        <label for="tab1" class="tabs_label">STANDARD</label>
          <div class="tab-content">
            <div id="Overview">
              <div id="Account-balance">Business Overview</div>
              <div id="Sales-overview">Accounts Receivable</div>
              <div id="Expenses-overview">Sales and Customers</div>
              <div id="Invoices">Accounts Payable</div>
              <div id="Outstanding-bills">Expenses and Suppliers</div>
              <div id="Profit-loss">Employees</div>
              <div id="Profit-loss">For my account</div>
              <div id="Profit-loss">Pay roll</div>
            </div>
          </div>

          <input type="radio" class="tabs_radio" name="tabs-example" id="tab2">
          <label for="tab2" class="tabs_label">CUSTOM REPORTS</label>
            <div class="tab-content">
              <div id="Overview">
                <div id="Account-balance"></div>
                <div id="Sales-overview"></div>
                <div id="Expenses-overview"></div>
                <div id="Invoices"></div>
                <div id="Outstanding-bills"></div>
                <div id="Profit-loss"></div>
              </div>
            </div>

            <input type="radio" class="tabs_radio" name="tabs-example" id="tab3">
            <label for="tab3" class="tabs_label">MANAGEMENT REPORTS</label>
              <div class="tab-content">
                <div id="Overview">
                  <div id="Account-balance"></div>
                  <div id="Sales-overview"></div>
                  <div id="Expenses-overview"></div>
                  <div id="Invoices"></div>
                  <div id="Outstanding-bills"></div>
                  <div id="Profit-loss"></div>
                </div>
              </div>
      </div>
    </div>
    <!-- JavaScript -->
 {% include 'includes/footer.html' %}