sowafinance/expenses/urls.py
from django.urls import path
from . import views
app_name='expenses'
# my urls
urlpatterns = [  
# expenses urls
    path('expenses/', views.expenses, name='expenses'),
    path('expenses/add/time-activity', views.add_time_activity, name='time-activity'),
    path('expenses/add/bill', views.add_bill, name='add-bill'),
    path('expenses/supplier-credit', views.supplier_credit, name='supplier-credit'),
    path('expenses/add/purchase_order', views.purchase_order, name='purchase_order'),
    path('expenses/pay_down_credit', views.pay_down_credit, name='pay-down-credit'),
    path('expenses/import_bills', views.import_bills, name='import-bills'),
    path('expenses/credit_card', views.credit_card, name='credit-card'),
    path('expenses/add/cheque', views.add_cheque, name='add-cheque'),
    path('expenses/add/expenses', views.add_expenses, name='add-expenses'),
]

sowafinance/sales/urls.py
from django.urls import path
from . import views


app_name='sales'
# my urls
urlpatterns = [  
# sales urls
    path('sales/', views.sales, name='sales'),
    path('sales/add/invoice', views.add_invoice, name='add-invoice'),
    path('sales/add/receipts', views.add_receipt, name='add-receipt'),
    path('sales/add/payments', views.add_payment, name='add-payments'),
    path('sales/add/invoice', views.add_invoice, name='add-invoice'),
    path('sales/invoices/', views.invoice_list, name='invoices'),
    path('sales/full-invoice-details/', views.full_invoice_details, name='full-invoice-details'),
    path('sales/individual-invoice/', views.individual_invoice, name='individual-invoice'),
    # path('receipts/', views.receipt, name='receipts'),
    path('receipts/add/receipt', views.add_receipt, name='add-receipt'),
    # path('payments/', views.payment, name='payments'),
    path('payments/add/payment', views.add_payment, name='add-payment'),
]

sowafinance/sowaAuth/urls.py
from django.urls import path
from . import views

# app name
app_name='sowaAuth'
urlpatterns = [    
    path('', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('otp/', views.verify_otp, name='otp'),
]

sowafinance/sowaf/urls.py
from django.urls import path
from . import views


app_name='sowaf'
# my urls
urlpatterns = [
    path('home/', views.home, name='home'),
    
    # asset urls
    path('assets/', views.assets, name='assets'),
    path('assets/add/asset', views.add_assests, name='add-asset'),
    path('assets/edit/<str:pk>/', views.edit_asset, name='edit-asset'),
    path('assets/delete/<str:pk>/', views.delete_asset, name='delete-asset'),
    path('assets/import/import-assets', views.import_assets, name='import-assets'),
    path('templates/assets/', views.download_assets_template, name='import_assets_template'),
    
    # customer urls
    path('customers/', views.customers, name='customers'),
    path('customers/add/', views.add_customer, name='add-customer'),
    path('customers/edit/<str:pk>/', views.edit_customer, name='edit-customer'),
    path('customers/delete/<str:pk>/', views.delete_customer, name='delete-customer'),
    path('customers/import/import-customers', views.import_customers, name='import-customers'),
    path('templates/customers/', views.download_customers_template, name='import_customers_template'),
    
    # clents urls
    path('clients/', views.clients, name='clients'),
    path('clients/add/', views.add_client, name='add-client'),
    path('clients/edit/<str:pk>/', views.edit_client, name='edit-client'),
    path('clients/delete/<str:pk>/', views.delete_client, name='delete-client'),
    path('clients/import/import-clients', views.import_clients, name='import-clients'), 
    path('templates/clients/', views.download_clients_template, name='import_clients_template'),
    
    # employee urls
    path('employees/', views.employee, name='employees'),
    path('employees/add/employee', views.add_employees, name='add-employee'),
    path('employees/edit/<str:pk>/', views.edit_employee, name='edit-employee'),
    path('employees/delete/<str:pk>/', views.delete_employee, name='delete-employee'),
    path('employees/import/import-employees', views.import_employees, name='import-employees'),
    path('templates/employees/', views.download_employees_template, name='import_employees_template'),
  
    # supplier urls
    path('suppliers/', views.supplier, name='suppliers'),
    path('suppliers/add/supplier', views.add_supplier, name='add-supplier'),
    path('suppliers/edit/<str:pk>', views.edit_supplier, name='edit-supplier'),
    path('suppliers/delete/<str:pk>', views.delete_supplier, name='delete-supplier'),
    path('suppliers/import/import-suppliers', views.import_suppliers, name='import-suppliers'),
    path('templates/suppliers/', views.download_suppliers_template, name='import_suppliers_template'),
    
 
        # expenses url
    path('expenses/', views.expenses, name='expenses'),
    # tasks url
    path('tasks/', views.tasks, name='tasks'),
    # taxes url
    path('taxes/', views.taxes, name='taxes'),

    # -------------------
    path('miscellaneous/', views.miscellaneous, name='miscellaneous'),
    # -------------
    path('reports/', views.reports, name='reports'),
    # -----------------
    
]

sowafinance/sowafinance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('sowaAuth.urls')),  # login, register, otp, etc.
    path('sowaAuth/', include('django.contrib.auth.urls')),
    # Nest all app URLs under 'sowaf/'
    path('sowaf/', include([
        path('', include('sowaf.urls')),         # dashboard and home
        path('sales/', include('sales.urls')),   # sales module
        path('expenses/', include('expenses.urls')),  # expenses
        path('inventory/', include('inventory.urls')),  # inventory
    ])),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sowafinance/expenses/models.py
from django.db import models

# Create your models here.

sowafinance/expenses/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from openpyxl import Workbook
from tempfile import NamedTemporaryFile
from datetime import datetime, timedelta
from django.utils import timezone
import openpyxl
import csv
import io
import os
from django.core.files import File
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# from . models import Newinvoice,InvoiceItem,Product,BundleItem
from sowaf.models import Newcustomer


# Expenses view
def expenses(request):
   
    return render(request, 'expenses.html', {})
def add_time_activity(request):
   
    return render(request, 'time_activity_form.html', {})
def add_bill(request):
   
    return render(request, 'bill_form.html', {})
def purchase_order(request):
   
    return render(request, 'purchase_order_form.html', {})
def supplier_credit(request):
   
    return render(request, 'supplier_credit_form.html', {})
def add_expenses(request):
   
    return render(request, 'expenses_form.html', {})
def pay_down_credit(request):
   
    return render(request, 'pay_down_credit_form.html', {})
def import_bills(request):
   
    return render(request, 'import_bills_form.html', {})
def credit_card(request):
   
    return render(request, 'credit_card_credit_form.html', {})
def add_cheque(request):
   
    return render(request, 'cheque_form.html', {})

sowafinance/expenses/templates/includes/sidebar.html
   {% load static %}
    <style>
    @media only screen and (max-width: 600px) {
  #sidebar{
    margin-top: 30%;
    padding-top: 50%;
    width: 4%;
    margin-left: 0;
  }
}
</style>
    <!-- sidebar -->
    <nav class="sidebar">
      <div class="menu_content" >
        <ul class="menu_items">
          <li class="item" id="sidebar">
            <div href="#" class="nav_link submenu_item">
              <span class="navlink_icon">
                <i class="bx bx-grid-alt"></i>
              </span>
              <span class="navlink">Overview</span>
              <i class="bx bx-chevron-right arrow-left"></i>
            </div>

            <ul class="menu_items submenu">
              <li class="item">
                <a href="./login_signup.html" class="nav_link">
                  <span class="navlink_icon">
                    <i class='bx bxs-user-account' ></i>
                  </span>
                  <span class="navlink">Accounts</span>
                </a>
              </li>   <li class="item">
                <a href="#" class="nav_link">
                  <span class="navlink_icon">
                    <i class='bx bxs-pie-chart-alt-2' ></i>
                  </span>
                  <span class="navlink">Insights</span>
                </a>
              </li>
            </ul>
          </li>
          <!-- end -->
        </ul>

        <ul class="menu_items">
          <div class="menu_title menu_editor"></div>
          <!-- duplicate these li tag if you want to add or remove navlink only -->
          <!-- Start -->
          <li class="item">
            <a href="{% url 'sowaf:home' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bx-home' ></i>
              </span>
              <span class="navlink">Home</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sowaf:tasks' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bx-task' ></i>
              </span>
              <span class="navlink">Tasks</span>
            </a>
          </li>
          <li class="item" >
            <a href="{% url 'sowaf:clients' %}" class="nav_link" id="">
              <span class="navlink_icon">
                <i class='bx bx-body'></i>
              </span>
              <span class="navlink">Clients</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sowaf:customers' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bx-user-voice'></i>
              </span>
              <span class="navlink">Customers</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sales:sales' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bx-money' ></i>
              </span>
              <span class="navlink">Sales</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sowaf:suppliers' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bxs-truck' ></i>
              </span>
              <span class="navlink">Suppliers</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'expenses:expenses' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bx-money-withdraw' ></i>
              </span>
              <span class="navlink">Expenses</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sowaf:employees' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bxs-briefcase' ></i>
              </span>
              <span class="navlink">Employees</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sowaf:reports' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bxs-report' ></i>
              </span>
              <span class="navlink">Reports</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sowaf:taxes' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bxs-wallet-alt' ></i>
              </span>
              <span class="navlink">Taxes</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sowaf:assets' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bx-building-house' ></i>
              </span>
              <span class="navlink">Assets</span>
            </a>
          </li>
          <li class="item">
            <a href="{% url 'sowaf:miscellaneous' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bxl-graphql' ></i>
              </span>
              <span class="navlink">Miscellaneous</span>
            </a>
          </li>
          
          <!-- End -->

        <ul class="menu_items">
          <div class="menu_title menu_setting"></div>
          <li class="item">
            <a href="#" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bx-help-circle' ></i>
              </span>
              <span class="navlink">Help</span>
            </a>
          </li>
          <li class="item mb-5">
            <a href="#" class="nav_link">
              <span class="navlink_icon">
                <i class="bx bx-cog"></i>
              </span>
              <span class="navlink">Setting</span>
            </a>
          </li>
          <li class="item mb-5">
            <a href="{% url 'sowaAuth:logout' %}" class="nav_link">
              <span class="navlink_icon">
                <i class='bx bx-log-out'></i>
              </span>
              <span class="navlink">Logout</span>
            </a>
          </li>
        </ul>

        <!-- Sidebar Open / Close -->
        <div class="bottom_content my-5">
          <div class="bottom expand_sidebar">
            <span> Expand</span>
            <i class='bx bx-log-in' ></i>
          </div>
          <div class="bottom collapse_sidebar">
            <span> Collapse</span>
            <i class='bx bx-log-out'></i>
          </div>
        </div>
        
      </div>
    </nav>